echo "Hola mundo con jenkins & Github con sh y sublimetext"
echo "Probando trigger desde Github y jenkins"
echo "Probando trigeer con webhook desde git y usando ngrok alas 11 pm _ me falto activar el trigger XD"
echo "Maia mirando el panorama XD 11pm"
echo "Holaaaaaaaaaaaaaaaaaaaaaaa"